tasks.withType(Test) {
    useJUnitPlatform()

    testLogging {
        exceptionFormat = 'full'
        events 'passed', 'skipped', 'failed'//, 'standardOut', 'standardError'
    }
}

apply plugin: 'com.adarshr.test-logger'
testlogger {
    theme 'mocha'
    showFullStackTraces true
    showStandardStreams true
    showPassedStandardStreams false
    showSkippedStandardStreams false
    showFailedStandardStreams true
}