plugins {
    id "groovy"
    id "cloud.wondrify.asset-pipeline"
}

apply plugin: "org.apache.grails.gradle.grails-web"
apply plugin: "org.apache.grails.gradle.grails-gsp"


version = project.projectVersion
group = "grails.app"

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation("org.apache.grails:grails-core")
    implementation("org.apache.grails:grails-logging")
    implementation("org.apache.grails:grails-databinding")
    implementation("org.apache.grails:grails-interceptors")
    implementation("org.apache.grails:grails-rest-transforms")
    implementation("org.apache.grails:grails-services")
    implementation("org.apache.grails:grails-url-mappings")
    implementation("org.apache.grails:grails-web-boot")
    implementation("org.apache.grails:grails-gsp")
    implementation("org.apache.grails:grails-layout")
    implementation("org.apache.grails:grails-data-hibernate5")
    implementation("org.apache.grails:grails-scaffolding")
    implementation("org.springframework.boot:spring-boot-autoconfigure")
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-logging")
    implementation("org.springframework.boot:spring-boot-starter-tomcat")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    console("org.apache.grails:grails-console")
    runtimeOnly("cloud.wondrify:asset-pipeline-grails")
    runtimeOnly("com.h2database:h2")
    runtimeOnly("org.apache.tomcat:tomcat-jdbc")
    runtimeOnly("org.fusesource.jansi:jansi")
    testImplementation("org.apache.grails:grails-testing-support-datamapping")
    testImplementation("org.apache.grails:grails-testing-support-web")

    integrationTestImplementation testFixtures("org.apache.grails:grails-geb")
    testImplementation("org.spockframework:spock-core")

    implementation project(':grails-web-console')
}

apply {
    from project.rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from project.rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
}

assets {
    minifyJs = true
    minifyCss = true
}

bootRun {
    // jvmArgs("-Xdebug", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005")
}